### ISSUE TITLE
Question: Why is it advised not to include static assets in production?

### ISSUE THREAD

**Issue by adam-beck** [DavidWells/isomorphic-react-example#8]
For the server there is this block of code

``` javascript
// Include static assets. Not advised for production
app.use(express.static(path.join(__dirname, 'public')));
```

and I was just wondering why it isn't advised to include the static assets for production.

**Comment by DavidWells** [comment]
Node isn't particularly meant for serving up static files, but it can.

It's advised to offload and serve static assets from something like nginx or a CDN.
